---
#- name: Install OpenJDK
#  apt: name=openjdk-{{java_version}}-jre-headless state=present
#  when: java_version != 'none'

- name: Fetch kafka binary package
  get_url: dest="{{ kafka_staging_dir }}/{{ kafka_tarball_name }}" url="{{kafka_url}}/{{kafka_tarball_name}}"
