---
#- name: Install OpenJDK
#  apt: name=openjdk-{{java_version}}-jre-headless state=present
#  when: java_version != 'none'

- name: Fetch kafka binary package
  get_url: dest="{{ kafka_tarball_location }}/{{ kafka_tarball_name }}" url="{{apache_mirror}}/kafka/{{kafka_version}}/{{kafka_tarball_name}}"
